var amarelo = ['#735A10','#F4D26C','#F2BE22','#736332','#Bf961B']
var azul = ['#0D4C73','#0D5673','#1790BF','#59C1D9','#F2D399']
var vermelho =['#400106','#CA414C','#BF0413','#401418','#BC030E']
var verde = ['#BFBFBF','#8AA6A3','#425f5d','#127369','#10403B']
var roxo = ['#74268C','#503359','#34113F','#7E508C','#B43BD9']
var laranja = ['#613D1E','#E6B68C','#E08E45','#614D3B','#AD6E36']
var cinza = ['#598091','#1D4B5E','#2A3D45','#2D7391','#87C4DE']

function corA(){
    let body = document.body;
    let main = document.getElementsByTagName('main')[0]
    let aside1 = document.getElementsByTagName('aside')[0]
    let aside2 = document.getElementsByTagName('aside')[1]
    let aside3 = document.getElementsByTagName('aside')[2]
    let aside4 = document.getElementsByTagName('aside')[3]
    let titulo1 = document.getElementsByTagName('h1')[2]
    let titulo2 = document.getElementsByTagName('h1')[3]
    let titulo3 = document.getElementsByTagName('h1')[4]
    let titulo4 = document.getElementsByTagName('h1')[5]
    body.style.background = amarelo[1]
    main.style.background = amarelo[4]
    aside1.style.background = amarelo[1]
    aside2.style.background = amarelo[1]
    aside3.style.background = amarelo[1]
    aside4.style.background = amarelo[1]
    titulo1.style.background = amarelo[0]
    titulo2.style.background = amarelo[0]
    titulo3.style.background = amarelo[0]
    titulo4.style.background = amarelo[0]
}

function corB(){
    let body = document.body;
    let main = document.getElementsByTagName('main')[0]
    let aside1 = document.getElementsByTagName('aside')[0]
    let aside2 = document.getElementsByTagName('aside')[1]
    let aside3 = document.getElementsByTagName('aside')[2]
    let aside4 = document.getElementsByTagName('aside')[3]
    let titulo1 = document.getElementsByTagName('h1')[2]
    let titulo2 = document.getElementsByTagName('h1')[3]
    let titulo3 = document.getElementsByTagName('h1')[4]
    let titulo4 = document.getElementsByTagName('h1')[5]
    body.style.background = azul[3]
    main.style.background = azul[2]
    aside1.style.background = azul[3]
    aside2.style.background = azul[3]
    aside3.style.background = azul[3]
    aside4.style.background = azul[3]
    titulo1.style.background = azul[0]
    titulo2.style.background = azul[0]
    titulo3.style.background = azul[0]
    titulo4.style.background = azul[0]
}

function corC(){
    let body = document.body;
    let main = document.getElementsByTagName('main')[0]
    let aside1 = document.getElementsByTagName('aside')[0]
    let aside2 = document.getElementsByTagName('aside')[1]
    let aside3 = document.getElementsByTagName('aside')[2]
    let aside4 = document.getElementsByTagName('aside')[3]
    let titulo1 = document.getElementsByTagName('h1')[2]
    let titulo2 = document.getElementsByTagName('h1')[3]
    let titulo3 = document.getElementsByTagName('h1')[4]
    let titulo4 = document.getElementsByTagName('h1')[5]
    body.style.background = vermelho[3]
    main.style.background = vermelho[2]
    aside1.style.background = vermelho[1]
    aside2.style.background = vermelho[1]
    aside3.style.background = vermelho[1]
    aside4.style.background = vermelho[1]
    titulo1.style.background = vermelho[0]
    titulo2.style.background = vermelho[0]
    titulo3.style.background = vermelho[0]
    titulo4.style.background = vermelho[0]
}

function corD(){
    let body = document.body;
    let main = document.getElementsByTagName('main')[0]
    let aside1 = document.getElementsByTagName('aside')[0]
    let aside2 = document.getElementsByTagName('aside')[1]
    let aside3 = document.getElementsByTagName('aside')[2]
    let aside4 = document.getElementsByTagName('aside')[3]
    let titulo1 = document.getElementsByTagName('h1')[2]
    let titulo2 = document.getElementsByTagName('h1')[3]
    let titulo3 = document.getElementsByTagName('h1')[4]
    let titulo4 = document.getElementsByTagName('h1')[5]
    body.style.backgroundColor = verde[1]
    main.style.background = verde[0]
    aside1.style.background = verde[1]
    aside2.style.background = verde[1]
    aside3.style.background = verde[1]
    aside4.style.background = verde[1]
    titulo1.style.background = verde[4]
    titulo2.style.background = verde[4]
    titulo3.style.background = verde[4]
    titulo4.style.background = verde[4]
}

function corE(){
    let body = document.body;
    let main = document.getElementsByTagName('main')[0]
    let aside1 = document.getElementsByTagName('aside')[0]
    let aside2 = document.getElementsByTagName('aside')[1]
    let aside3 = document.getElementsByTagName('aside')[2]
    let aside4 = document.getElementsByTagName('aside')[3]
    let titulo1 = document.getElementsByTagName('h1')[2]
    let titulo2 = document.getElementsByTagName('h1')[3]
    let titulo3 = document.getElementsByTagName('h1')[4]
    let titulo4 = document.getElementsByTagName('h1')[5]
    body.style.backgroundColor = roxo[3]
    main.style.background = roxo[1]
    aside1.style.background = roxo[3]
    aside2.style.background = roxo[3]
    aside3.style.background = roxo[3]
    aside4.style.background = roxo[3]
    titulo1.style.background = roxo[2]
    titulo2.style.background = roxo[2]
    titulo3.style.background = roxo[2]
    titulo4.style.background = roxo[2]
}

function corF(){
    let body = document.body;
    let main = document.getElementsByTagName('main')[0]
    let aside1 = document.getElementsByTagName('aside')[0]
    let aside2 = document.getElementsByTagName('aside')[1]
    let aside3 = document.getElementsByTagName('aside')[2]
    let aside4 = document.getElementsByTagName('aside')[3]
    let titulo1 = document.getElementsByTagName('h1')[2]
    let titulo2 = document.getElementsByTagName('h1')[3]
    let titulo3 = document.getElementsByTagName('h1')[4]
    let titulo4 = document.getElementsByTagName('h1')[5]
    body.style.backgroundColor = laranja[1]
    main.style.background = laranja[2]
    aside1.style.background = laranja[1]
    aside2.style.background = laranja[1]
    aside3.style.background = laranja[1]
    aside4.style.background = laranja[1]
    titulo1.style.background = laranja[4]
    titulo2.style.background = laranja[4]
    titulo3.style.background = laranja[4]
    titulo4.style.background = laranja[4]
}

function corG(){
    let body = document.body;
    let main = document.getElementsByTagName('main')[0]
    let aside1 = document.getElementsByTagName('aside')[0]
    let aside2 = document.getElementsByTagName('aside')[1]
    let aside3 = document.getElementsByTagName('aside')[2]
    let aside4 = document.getElementsByTagName('aside')[3]
    let titulo1 = document.getElementsByTagName('h1')[2]
    let titulo2 = document.getElementsByTagName('h1')[3]
    let titulo3 = document.getElementsByTagName('h1')[4]
    let titulo4 = document.getElementsByTagName('h1')[5]
    body.style.backgroundColor = cinza[4]
    main.style.background = cinza[0]
    aside1.style.background = cinza[4]
    aside2.style.background = cinza[4]
    aside3.style.background = cinza[4]
    aside4.style.background = cinza[4]
    titulo1.style.background = cinza[2]
    titulo2.style.background = cinza[2]
    titulo3.style.background = cinza[2]
    titulo4.style.background = cinza[2]
}